### ISSUE TITLE
font error in Wine

### ISSUE THREAD

**Issue by dezanche** [nikolaygekht/ballistic.calculator.app#4]
I'm getting the following error starting the app in Wine:

> 2024-10-23` 14:56:15.672 -06:00 [FTL] Unhandled exception
> System.ArgumentException: Font '?' cannot be found.
>    at System.Drawing.FontFamily.GetGdipGenericSansSerif()
>    at System.Drawing.FontFamily.CreateFontFamily(String name, FontCollection fontCollection)
>    at System.Drawing.Font.Initialize(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
>    at System.Drawing.Font..ctor(String familyName, Single emSize, FontStyle style, GraphicsUnit unit)
>    at ScottPlot.FormsPlot.InitializeComponent()
>    at ScottPlot.FormsPlot..ctor()
>    at BallisticCalculatorNet.InputPanels.ChartControl.InitializeComponent() in D:\develop\homeapps\BallisticCalculator1\BallisticCalculatorNet.InputPanels\ChartControl.Designer.cs:line 31
>    at BallisticCalculatorNet.InputPanels.ChartControl..ctor() in D:\develop\homeapps\BallisticCalculator1\BallisticCalculatorNet.InputPanels\ChartControl.cs:line 77
>    at BallisticCalculatorNet.TrajectoryForm.InitializeComponent() in D:\develop\homeapps\BallisticCalculator1\BallisticCalculatorNet\TrajectoryForm.Designer.cs:line 36
>    at BallisticCalculatorNet.TrajectoryForm..ctor() in D:\develop\homeapps\BallisticCalculator1\BallisticCalculatorNet\TrajectoryForm.cs:line 94
>    at BallisticCalculatorNet.AppForm..ctor() in D:\develop\homeapps\BallisticCalculator1\BallisticCalculatorNet\AppForm.cs:line 31
>    at BallisticCalculatorNet.Program.Main(String[] args) in D:\develop\homeapps\BallisticCalculator1\BallisticCalculatorNet\Program.cs:line 123

I tried a few fixes suggested in various forums to get Wine to find a suitable replacement font but it still gives that error.
Any ideas?

**Comment by dezanche** [comment]
Thanks for getting back to me
It's linux Mint Debian edition (LMDE) 6
cinnamon 6.4.8
WinE 8.0 (Debian 8.0-repack-4)
